[Interface]
PrivateKey = <REMOTE_PRIVATE_KEY>
Address = 10.77.0.21/32

[Peer]
PublicKey = <AUTHORITY_PUBLIC_KEY>
Endpoint = <AUTHORITY_PUBLIC_IP>:51820
AllowedIPs = 10.77.0.1/32
PersistentKeepalive = 25
